import { Geist, Geist_Mono } from "next/font/google";
import { FaHome, FaBook, FaNewspaper, FaUsers, FaEnvelope, FaInfoCircle, FaFlask, FaGraduationCap, FaChalkboardTeacher } from "react-icons/fa";
import { AiOutlineMail, AiOutlinePhone } from "react-icons/ai";
import Link from "next/link";
import "./globals.css";
import Navbar from '../components/Navbar'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Comuter Science And Engneering",
  description: "Generated by create next app",
  icons: {
    icon: '/logo_msu.png', // Path from the public folder
    // You can also add other icon types:
    shortcut: '/logo_msu.png',
    apple: '/apple-touch-icon.png',
  },
};


const NavLink = ({ href, icon, text }) => (
  <li>
    <Link href={href} className="flex items-center text-xl py-3 px-4 hover:bg-blue-600 hover:text-white transition-all rounded text-gray-700">
      {icon}
      <span className="ml-2">{text}</span>
    </Link>
  </li>
);


const Footer = () => {

  return (
    <footer className="bg-sky-950 text-white">
      <div className="max-w-6xl mx-auto py-16 px-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Contact Form */}
          <div>
            <h3 className="text-xl font-bold mb-4">Contact Us</h3>
            <form  className="space-y-4">
              <input
                type="text"
                placeholder="Your Name"
                className="w-full p-2 rounded text-black placeholder-black"
                required
              />
              <input
                type="email"
                placeholder="Your Email"
                className="w-full p-2 rounded text-black placeholder-black"
                required
              />
              <textarea
                placeholder="Your Message"
                className="w-full p-2 rounded text-black placeholder-black"
                rows={4}
                required
              />
              <button
                type="submit"
                className="bg-white text-black px-6 py-2 rounded hover:bg-blue-100 transition-colors"
              >
                Send Message
              </button>
            </form>
          </div>

          {/* Quick Links */}
          <div>
            <h3 className="text-xl font-bold mb-4">Quick Links</h3>
            <ul className="space-y-2">
              <li><Link href="#" className="hover:text-blue-300">Admissions</Link></li>
              <li><Link href="#" className="hover:text-blue-300">Programs</Link></li>
              <li><Link href="#" className="hover:text-blue-300">Research</Link></li>
              <li><Link href="#" className="hover:text-blue-300">Alumni</Link></li>
            </ul>
          </div>

          {/* Contact Info */}
          <div>
            <h3 className="text-xl font-bold mb-4">Contact Information</h3>
            <div className="space-y-4">
              <div className="flex items-center">
                <AiOutlineMail className="mr-2" />
                <span>info@msubaroda</span>
              </div>
              <div className="flex items-center">
                <AiOutlinePhone className="mr-2" />
                <span>+91 9994567423</span>
              </div>
              <p className="text-sm text-blue-300">
                Kalabhavan,Kirti Stambh,Vadodara,India
              </p>
            </div>
          </div>
        </div>

        {/* Copyright */}
        <div className="border-t border-blue-700 mt-8 pt-8 text-center text-blue-300">
          &copy; {new Date().getFullYear()} Computer Science and Engineering. All rights reserved.
        </div>
      </div>
    </footer>
  );
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Navbar/>
        {children}
      <Footer />
      </body>
    </html>
  );
}
